### ISSUE TITLE
btoa is not defined.

### ISSUE THREAD

**Issue by atiilla** [minhazmiraz/file-extension-icon-JS#1]
This library is not working in a next.js(react based) app.

**Comment by hrishikesh-k** [comment]
I was using this in a client-side script but bundle size went up by 4 MB!, so decided to use it in a serverless function. It was working fine in browser, but failed in lambda, because of this error. The problem is, https://www.w3schools.com/jsref/met_win_btoa.asp appears to be available only in browsers.

Chances are, you're using this library in one of your server side routes, which is why it fails.

**Comment by minhazmiraz** [comment]
Please check now in latest version (v1.1.6).
